default_install_hook_types:
  - pre-commit

repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace         # Removes trailing whitespace from files
      - id: end-of-file-fixer           # Ensures files end with a single newline
      - id: check-yaml                  # Validates YAML syntax
      - id: check-added-large-files     # Warns about adding large files to the repo

  # Terraform-specific hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2 # Check the latest version at: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt               # Formats Terraform code
      - id: terraform_docs              # Updates Terraform documentation
        exclude: ^examples/             # Exclude examples from documentation generation
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --args=--hide providers      # Hides the 'providers' section from the output
      - id: terraform_tflint             # Runs tflint for linting Terraform code
        exclude: ^examples/             # Exclude examples from documentation generation
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl # Specifies custom tflint configuration file

  # Pre-commit hook for Trivy
  - repo: https://github.com/aquasecurity/trivy
    rev: v0.58.2 # Check for the latest version at https://github.com/aquasecurity/trivy/releases
    hooks:
      - id: trivy-config
        name: Trivy Scan for Terraform
        entry: trivy config
        args:
          - --severity=HIGH,CRITICAL   # Only report high and critical severity issues
          - --skip-dirs=.terraform     # Exclude `.terraform` directory
          - --exit-code=0              # Do not block the commit; warnings only
        exclude: ^example/.*$           # Exclude files in the 'example' directory
        pass_failing: true              # Allow the hook to pass even if issues are found

  # Pre-commit hook for checkov
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.358 # Check for the latest version at https://github.com/bridgecrewio/checkov/releases
    hooks:
      - id: checkov
        args:
          - --quiet                # Suppress non-critical output
        files: \.tf$               # Applies only to Terraform files
        exclude: ^example/.*$      # Excludes files in 'example' directory
